# - hosts: web
#   tasks:
#   - name: Ensure iproute2 is installed on every node.
#     apt:
#       name: iproute2
#       state: present
- hosts: web[0]
  tags: hostvars
  name: Run only on first host
  tasks:
  - name: Iterating over a map yields the keys
    debug:
      msg: >
        Host: {{ item }}
    with_items: >
      {{ hostvars }}
  - name: >-
      Use subscript to access entries.
      NB: This task requires iproute2 installed on the remote host.
    debug:
      msg: >
       address: {{ hostvars[item]['ansible_default_ipv4']['address'] }}
    with_items: >
      {{ groups['web'] }}


- hosts: web[0]
  tags: filters
  name: Get a list of defined host IPs.
  tasks:
  - name: Using filters
    debug:
      msg: >
       {{ groups['web'] |
          map('extract', hostvars, ['ansible_default_ipv4', 'address']) |
          reject('undefined') |
          list }}
